### ISSUE TITLE
Update Version in manifest.json for release workflow

### ISSUE THREAD

**Issue by dahlb** [fuatakgun/kia_uvo#172]
HASC lists the git version but HA doesn't have matching version, having the HA version being accurate could be very helpful in bug reporting.

https://github.com/jossef/action-semantic-release-info creates a github workflow variable of ${{steps.semantic_release_info.outputs.version}} that we should be able to sed or something similiar into the manifest.json file.

**Comment by dahlb** [comment]
@cdnninja I can take a look at fixing this but it might be easier for you as you've already worked with this library, ps liking the templates :)

**Comment by cdnninja** [comment]
I actually started this here: https://github.com/cdnninja/kia_uvo/commit/82717edba6ee7a272e6872fad7e156b46bf77977
What I don't know how to do yet is edit the manifest.json using that variable.    If you are familiar with that part it would help!

**Comment by cdnninja** [comment]
As for the templates I took them from @fuatakgun's other project.  Saw he had them setup so just tweaked a bit.

**Comment by dahlb** [comment]
using sed this works locally
```
export TEST=1.0.1 && sed -i "s/\"version\": \".*\",/\"version\": \"${TEST}\",/g" custom_components/kia_uvo/manifest.json 
```

so if you have a workflow image that comes with sed this should update the file, the commit and push examples are listed in jossef's readme
```
sed -i "s/\"version\": \".*\",/\"version\": \"${{steps.semantic_release_info.outputs.version}}\",/g" custom_components/kia_uvo/manifest.json 
```

**Comment by dahlb** [comment]
looks like this runs on ubuntu, not sure if sed comes with that or not by default so I added the first two lines to install sed assuming it isn't already available (might work without those apt-get lines, would be a little faster if they aren't needed)
```
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Gets semantic release info
        id: semantic_release_info
        uses: jossef/action-semantic-release-info@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Update Manifest
        run: |
          sudo apt-get update -y
          sudo apt-get install -y sed
          sed -i "s/\"version\": \".*\",/\"version\": \"${{steps.semantic_release_info.outputs.version}}\",/g" custom_components/kia_uvo/manifest.json 

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "docs(): bumping release ${{ steps.semantic_release_info.outputs.git_tag }}"
          git tag ${{ steps.semantic_release_info.outputs.git_tag }}
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ github.token }}
          tags: true

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.semantic_release_info.outputs.git_tag }}
          release_name: ${{ steps.semantic_release_info.outputs.git_tag }}
          body: ${{ steps.semantic_release_info.outputs.notes }}
          draft: false
          prerelease: false
```
does this work?
