### ISSUE TITLE
No odometer entity for Hyundai Santa Fe 2020

### ISSUE THREAD

**Issue by tucknology** [fuatakgun/kia_uvo#177]
**Region and Brand of car**
USA, Hyundai Santa Fe 2020

**Describe the bug**
There is no odometer entity for my vehicle. 

**Expected behavior**
Odometer entity shows car's mileage. 

**Screenshots**
<img width="482" alt="image" src="https://user-images.githubusercontent.com/19787615/143291764-c3ef3716-f20f-4922-9bc5-e81aaaae7d58.png">

**Comment by cdnninja** [comment]
Are you willing to do some testing for this?   We as a dev group don't have a USA Hyundai to test with.   The current setup is pretty basic but lots more can be added.   Someone else did the hard work of getting it this far. 

Could you post your raw data from the developer tool on the left of home assistant and then select the data entity?  Please remove the GPS details if it exists in that.

**Comment by tucknology** [comment]
Sure I'm happy to test however I can. Here's the data (I replaced GPS with similar but inaccurate data):

```
vehicle_data:
  vehicleStatus:
    dateTime: '20211124030720'
    acc: false
    defrostStatus: 'false'
    transCond: true
    doorLockStatus: 'true'
    doorOpen:
      frontRight: 0
      frontLeft: 0
      backLeft: 0
      backRight: 0
    battery:
      batSoc: 77
      batState: 0
      sjbDeliveryMode: 1
    vehicleLocation:
      coord:
        lon: 97
        type: 0
        lat: 31
    ign3: false
    ignitionStatus: 'false'
    lowFuelLight: false
    sideBackWindowHeat: 0
    dte:
      unit: 3
      value: 189
    engine: false
    hoodOpen: false
    airConditionStatus: 'false'
    steerWheelHeat: 0
    trunkOpen: false
    doorLock: 'true'
    airCtrlOn: false
    airTemp:
      unit: 0
      hvacTempType: 1
      value: LO
    sleepModeCheck: false
    defrost: false
    tirePressureLamp:
      tirePressureWarningLampRearLeft: 0
      tirePressureWarningLampFrontLeft: 0
      tirePressureWarningLampFrontRight: 0
      tirePressureWarningLampAll: 0
      tirePressureWarningLampRearRight: 0
    trunkOpenStatus: 'false'
    time: '20211124030720'
    date: '20211124030720'
vehicle_name: 2020 SANTA FE
friendly_name: Hyundai Santa Fe Data

```
