### ISSUE TITLE
Missing Range (Petrol only)

### ISSUE THREAD

**Issue by holdestmade** [fuatakgun/kia_uvo#5]
Looks great so far, I'm currently using NR and Bluelinky so this is a great progression

There is a missing entity for me, the fuel range, signified in the vehicle data as `dte: value:` `unit: 3` is miles.
Also would it be possible for an option for the odometer to be in miles also ? No problem if not, I'll just create a template sensor.

```
vehicle_data: 
vehicleLocation:
  coord:
    lat: xxxxxxxxx
    lon: -xxxxxxxxx
    alt: 0
    type: 0
  head: 2
  speed:
    value: 0
    unit: 1
  accuracy:
    hdop: 10
    pdop: 10
  time: '20210410224324'
vehicleStatus:
  airCtrlOn: false
  engine: false
  doorLock: true
  doorOpen:
    frontLeft: 0
    frontRight: 0
    backLeft: 0
    backRight: 0
  trunkOpen: false
  airTemp:
    value: 01H
    unit: 0
    hvacTempType: 1
  defrost: false
  lowFuelLight: false
  acc: false
  hoodOpen: false
  steerWheelHeat: 0
  sideBackWindowHeat: 0
  dte:
    value: 106
    unit: 3
  tirePressureLamp:
    tirePressureLampAll: 0
    tirePressureLampFL: 0
    tirePressureLampFR: 0
    tirePressureLampRL: 0
    tirePressureLampRR: 0
  battery:
    batSoc: 61
    batState: 0
  time: '20210410224323'
odometer:
  value: 4175.7
  unit: 1
```

**Comment by fuatakgun** [comment]
one question, about unit, is your odometer value (4175) is in miles or km?

**Comment by badguy99** [comment]
For me, Kia is returning Odometer in km (unit: 1) and evModeRange etc in miles (unit: 3)
I'm just coding up a fix for the units, so it displays km or mi depending on the returned value - should have a PR shortly.

**Comment by fuatakgun** [comment]
your range has been fixed in latest version, please update.
In the meantime, i am looking at unit

**Comment by holdestmade** [comment]
Hi, the odometer is shown in km.

**Comment by badguy99** [comment]
> Edit: Ok, please go ahead with PR for the units and let me know when it is ready

done, see #6 - it will need a slight modification as mentioned in the PR - the code base is moving fast 😄

**Comment by fuatakgun** [comment]
> > Edit: Ok, please go ahead with PR for the units and let me know when it is ready
> 
> done, see #6 - it will need a slight modification as mentioned in the PR - the code base is moving fast 😄

I was working on a different solution and planning to create another PR, but by mistake I have merged it.
Can you please take a look at this and share your thoughts? https://github.com/fuatakgun/kia_uvo/commit/54416d174f4c3af686109505d8cb3cd53a46be9e

**Comment by badguy99** [comment]
It looks good to me. If it works, I'm good with the solution - many ways to get the same end result. 

I'd probably import the "km" and "mi" strings from homeassistant.const but that's just because I prefer importing the strings from there if they exist, and then have the following just after the imports in the file - 
`DISTANCE_UNITS = {1: LENGTH_KILOMETERS, 3: LENGTH_MILES}`

and then instead of lines 93-96 I think you can just have:
`self._unit = DISTANCE_UNITS[found_unit]`
in a similar way to what was in my PR, but I'm fine with the way you've done it too.

**Comment by fuatakgun** [comment]
Will improve based on your comments, thanks a lot

**Comment by holdestmade** [comment]
> your range has been fixed in latest version, please update.
> In the meantime, i am looking at unit.
> [5a67b74](https://github.com/fuatakgun/kia_uvo/commit/5a67b7423f1e2de8e37805c4429a553b5557104e)
> 
> Edit: Ok, please go ahead with PR for the units and let me know when it is ready

Just updated, the range says Not Applicable mi

**Comment by fuatakgun** [comment]
can you please double check now? should be fixed by this commit: https://github.com/fuatakgun/kia_uvo/commit/348ff4f1ed4d254e685c99108a2f71d7c8fd11c2

**Comment by holdestmade** [comment]
No still the same I'm afraid. 348ff4f

**Comment by fuatakgun** [comment]
if you can update your `configuration.yaml` like this, we can get more information in Configuration -> Logs page
```
logger:
  default: warning
  logs:
    custom_components.kia_uvo: debug
```
