### ISSUE TITLE
Car Battery entity is orphaned

### ISSUE THREAD

**Issue by JamesT42** [fuatakgun/kia_uvo#76]
Hi!

After updating from a version from mid August to the last one the Car Battery entity went from working perfectly fine to being unavailable/ orphaned.

And ideas as to why?

Thanks for your awesome work.
James

**Comment by cdnninja** [comment]
Europe or Canada? I would think we would also need your data output.  @fuatakgun  is battery working for you after the filters were added awhile back?

**Comment by fuatakgun** [comment]
i have a plugin hybrid and all is working good for me.

![Screenshot_2021-10-03-22-20-09-493_io.homeassistant.companion.android.jpg](https://user-images.githubusercontent.com/11085566/135770228-355240a8-7ce3-404c-bf37-1172023d42e5.jpg)

**Comment by JamesT42** [comment]
> Europe or Canada? I would think we would also need your data output. @fuatakgun is battery working for you after the filters were added awhile back?

Europe. How do I get the data?

**Comment by fuatakgun** [comment]
Go to developer tools page, select `binary_sensor.nickname_data` entity and dump the state attributes here. My sensor is called `binary_sensor.niro_data`

**Comment by JamesT42** [comment]
```
vehicle_data:
  vehicleLocation:
    coord:
      lat: x
      lon: x
      alt: x
      type: 0
    head: 98
    speed:
      value: 0
      unit: 0
    accuracy:
      hdop: 10
      pdop: 10
    time: '20211003225950'
    geocodedLocation:
      place_id: x
      licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
      osm_type: way
      osm_id: x
      lat: x
      lon: x
      display_name: >-
x
      address:
        house_number: x
        road: x
        suburb: x
        city: x
        state: x
        postcode: x
        country: x
        country_code: x
      boundingbox:
        - x
        - 'x
        - 'x
        - x
  vehicleStatus:
    airCtrlOn: false
    engine: false
    doorLock: true
    doorOpen:
      frontLeft: 0
      frontRight: 0
      backLeft: 0
      backRight: 0
    trunkOpen: false
    airTemp:
      value: 02H
      unit: 0
      hvacTempType: 1
    defrost: false
    acc: false
    evStatus:
      batteryCharge: false
      batteryStatus: 47
      batteryPlugin: 0
      remainTime2:
        etc1:
          value: 21
          unit: 1
        etc2:
          value: 950
          unit: 1
        etc3:
          value: 220
          unit: 1
        atc:
          value: 2
          unit: 1
      drvDistance:
        - rangeByFuel:
            evModeRange:
              value: 153
              unit: 1
            totalAvailableRange:
              value: 153
              unit: 1
          type: 2
      reservChargeInfos:
        reservChargeInfo:
          reservChargeInfoDetail:
            reservInfo:
              day:
                - 2
                - 3
                - 4
              time:
                time: '0830'
                timeSection: 0
            reservChargeSet: false
            reservFatcSet:
              defrost: false
              airTemp:
                value: 10H
                unit: 0
              airCtrl: 1
              heating1: 0
        offpeakPowerInfo:
          offPeakPowerTime1:
            starttime:
              time: '1200'
              timeSection: 0
            endtime:
              time: '1200'
              timeSection: 0
          offPeakPowerFlag: 0
        reserveChargeInfo2:
          reservChargeInfoDetail:
            reservInfo:
              day:
                - 2
                - 3
                - 4
              time:
                time: '1200'
                timeSection: 0
            reservChargeSet: false
            reservFatcSet:
              defrost: false
              airTemp:
                value: 10H
                unit: 0
              airCtrl: 1
              heating1: 0
        reservFlag: 0
        ect:
          start:
            day: 0
            time:
              time: '0000'
              timeSection: 0
          end:
            day: 0
            time:
              time: '0000'
              timeSection: 0
        targetSOClist:
          - targetSOClevel: 100
            dte:
              rangeByFuel:
                evModeRange:
                  value: 340
                  unit: 1
                totalAvailableRange:
                  value: 340
                  unit: 1
              type: 2
            plugType: 1
          - targetSOClevel: 90
            dte:
              rangeByFuel:
                evModeRange:
                  value: 302
                  unit: 1
                totalAvailableRange:
                  value: 302
                  unit: 1
              type: 2
            plugType: 0
      chargePortDoorOpenStatus: 2
    ign3: true
    hoodOpen: false
    steerWheelHeat: 0
    sideBackWindowHeat: 0
    tirePressureLamp:
      tirePressureLampAll: 0
    battery:
      batState: 1
      sjbDeliveryMode: 0
      batSignalReferenceValue:
        batWarning: 0
      powerAutoCutMode: 2
    lampWireStatus:
      stopLamp:
        stopLampStatus: false
        leftLamp: false
        rightLamp: false
      headLamp:
        headLampStatus: false
        leftLowLamp: false
        rightLowLamp: false
        leftHighLamp: false
        rightHighLamp: false
        leftBifuncLamp: false
        rightBifuncLamp: false
      turnSignalLamp:
        turnSignalLampStatus: false
        leftFrontLamp: false
        rightFrontLamp: false
        leftRearLamp: false
        rightRearLamp: false
    smartKeyBatteryWarning: false
    washerFluidStatus: false
    breakOilStatus: false
    sleepModeCheck: false
    time: '20211003225951'
    remoteWaitingTimeAlert:
      remoteControlAvailable: 1
      remoteControlWaitingTime: 168
      elapsedTime: '03:55:10'
    systemCutOffAlert: 0
    tailLampStatus: 0
    hazardStatus: 0
  odometer:
    value: x
    unit: 1
vehicle_name: IONIQ 5
friendly_name: IONIQ 5 Data
```
I had to delete some personal data (marked by x)

**Comment by fuatakgun** [comment]
Apparently kia had removed this information from its response.

Your battery section
```
    battery:

      batState: 1

      sjbDeliveryMode: 0

      batSignalReferenceValue:

        batWarning: 0

      powerAutoCutMode: 2
```

And compare it with mine
```
battery:
      batSoc: 90
      batState: 0
```


You don't have battery level (90% in my case) but only its state. i will decompose the meaning of `batState` and create a new sensor accordingly, but no more battery state for ev owners :-) nothing we can do on this
